---
title: "how-use-the-package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{how-use-the-package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rlgd)
```


```{r}
data("breast_cancer")
```

```{r}
x <- as.matrix(breast_cancer[1:10,1:4])
y <- breast_cancer[1:10,"classe"]
y <- as.matrix(ifelse(y$classe=="malignant",1,0))
theta <- as.matrix(rnorm(n = dim(x)[2], mean = 0, sd = 1)) 
```


```{r}
sigmoid(2)
```

```{r}
x_dot_theta(x, theta)
```

```{r}
probability(x,theta)
```

```{r}
probability(x, theta) - y
```


```{r}
cost_function(x,y,theta)
```

```{r}
mini_batch_gradient_descent(x, y, theta, learning_rate=0.01, max_iter=10, batch_size =
                              2, tol=1e-4)
```

```{r}
rlgd.fit <- function(formula, data, mode, batch_size, learning_rate = 0.5,
                     max_iter = 100, tol = 1e-4,ncores=1) {
  x_y <- get_x_y(formula, data)

  x <- x_y$features
  y <- x_y$target
  y_name <- x_y$y_name
  x_names <- x_y$x_names


  initial_theta <- as.matrix(rnorm(n = dim(x)[2], mean = 0, sd = 1))


  if (mode == "batch" || (mode == "mini-batch" && batch_size >= nrow(y))) {
    gradient_descent <- batch_gradient_descent(x, y, initial_theta, learning_rate, max_iter, tol)
  } else if (mode == "online" || (mode == "mini-batch" && batch_size == 1)) {
    gradient_descent <- stochastic_gradient_descent(x, y, initial_theta, learning_rate, max_iter, tol)
  } else if (mode == "mini-batch") {
    gradient_descent <- mini_batch_gradient_descent(x, y, initial_theta, learning_rate, max_iter, batch_size, tol)
  } else {
    return("erreur")
  }

  # Creation of the instance
  inst <- list(formula = formula, x = x, y = y, y_name = y_name, x_names = x_names, mode = mode, batch_size = batch_size, learning_rate = learning_rate, max_iter = max_iter, # nolint
               initial_theta = initial_theta, theta = gradient_descent[[1]], cost_history = gradient_descent[[2]]
  )

  attr(inst, "class") <- "Reg.Log"
  return(inst)
}
```




```{r}
#rlgd.fit(classe~., breast_cancer, "batch", batch_size=2, learning_rate = 0.1,
                     #max_iter = 100, tol = 1e-4,ncores=1)
```

