---
title: "how-use-the-package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{how-use-the-package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rlgd)
```


```{r}
data("breast_cancer")
```

```{r}
x <- as.matrix(breast_cancer[1:10,1:4])
y <- breast_cancer[1:10,"classe"]
y <- as.matrix(ifelse(y$classe=="malignant",1,0))
theta <- as.matrix(rnorm(n = dim(x)[2], mean = 0, sd = 1)) 
```


```{r}
sigmoid(2)
```

```{r}
x_dot_theta(x, theta)
```

```{r}
probability(x,theta)
```


```{r}
cost_function(x,y,theta)
```

```{r}
mini_batch_gradient_descent <- function(x, y, theta, learning_rate, max_iter,
                                        batch_size, tol) {

    cost_history <- c()
    m <- nrow(y)
    iter <- 0
    converge <- FALSE
    theta_list <- c()

    while ((iter < max_iter) && (converge == FALSE)) {
        # Shuffle data
        iter <- iter + 1
        random_index <- sample(x = m, size = m)
        x <- as.matrix(x[random_index, ])
        y <- as.matrix(y[random_index, ])
        x_i <- c()
        y_i <- c()

        index <- seq(1, m, batch_size - 1)

        for (j in 1:trunc(m / batch_size)) {
            y_i <- as.matrix(y[index[[j]]:index[[j + 1]], ])
            x_i <- as.matrix(x[index[[j]]:index[[j + 1]], ])
            theta <- theta - learning_rate * gradient(x_i, y_i, theta)
        }
        cost_history <- c(cost_history, cost_function(x_i, y_i, theta))

        theta_list <- append(theta_list, theta)

        if (sum(abs(theta_list[length(theta_list)] - theta_list[length(theta_list)-1]))
            < tol) {
            converge <- TRUE
        }

    }
    return(list(theta = theta, cost_history = cost_history))
}
```

```{r}
mini_batch_gradient_descent(x, y, theta, learning_rate=0.01, max_iter=10, batch_size =
                              32, tol=1e-4)
```

